### ISSUE TITLE
Bug when opening stats right after starting program

### ISSUE THREAD

**Issue by guidopetri** [ChrisK91/CardHeatmap#2]
Hey,

I got this bug right after opening Anki, clicking on a deck and then opening the statistics page.

```
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt\webview.py", line 152, in _linkHandler
  File "aqt\toolbar.py", line 74, in _linkHandler
  File "aqt\toolbar.py", line 94, in _statsLinkHandler
  File "aqt\main.py", line 732, in onStats
  File "C:\Users\Laptop\AppData\Roaming\Anki2\addons\review_heatmap\main.py", line 340, in my_statswindow_init
    self.refresh()
  File "aqt\stats.py", line 89, in refresh
  File "anki\stats.py", line 118, in report
  File "anki\hooks.py", line 61, in repl
  File "C:\Users\Laptop\AppData\Roaming\Anki2\addons\review_heatmap\main.py", line 288, in my_reps_graph
    ret = _old(self)
  File "anki\hooks.py", line 61, in repl
  File "C:\Users\Laptop\AppData\Roaming\Anki2\addons\cardheatmap\cardheatmap.py", line 56, in injectHeatmapGraph
    tooltip("No cards found to show on heatmap")
NameError: global name 'tooltip' is not defined
```

Thanks for making this addon - I really enjoy it! Hope my bug report helps!

edit: it seems opening the browser, then going to the stats page fixes the issue.
edit2: seems like opening a parent deck that doesn't have any cards by itself (only the ones in subdecks) causes the issue.

**Comment by ChrisK91** [comment]
That's an interesting issue... I will look into it. It might take a while, since I'm currently not at home :/ But thanks for your report!
